#ifndef CPP_VIRTUAL_MACHINE_ERRORS_H
#define CPP_VIRTUAL_MACHINE_ERRORS_H

typedef enum error_type {
    SUCCESS = 0,
    TARGET_ADDRESS_FULL = 1,
    FILE_NOT_PROVIDED,
    FILE_NOT_FOUND,
    INVALID_ADDRESS = 100,
    INVALID_INSTRUCTION,
    STACK_OVERFLOW,
    STACK_UNDERFLOW
}error_type;

#endif
