#ifndef CPP_VIRTUAL_MACHINE_ERRORS_H
#define CPP_VIRTUAL_MACHINE_ERRORS_H

typedef enum error_type {
    NO_TARGET_FILE_PROVIDED = 1,
    INVALID_ADDRESS,
    INVALID_INSTRUCTION,
    TARGET_ADDRESS_FULL,
    FILE_NOT_FOUND,
    STACK_OVERFLOW,
    STACK_UNDERFLOW
}error_type;

#endif
